#!/usr/bin/env python3
"""Generate theme.css from a design.json file.

Usage: python3 gen-theme.py <design.json> <output.css>

Produces a self-contained theme.css with:
  - :root {} block with all standard + custom CSS variables
  - @theme inline {} block mapping custom tokens to Tailwind classes
  - NO .dark {} block (dark mode is not supported)
"""
import json
import sys

# Standard semantic tokens — these are mapped in styles.css, not here
STANDARD_COLOR_MAPPING = [
    ("background", "background"),
    ("foreground", "foreground"),
    ("card", "card"),
    ("card-foreground", "cardForeground"),
    ("popover", "popover"),
    ("popover-foreground", "popoverForeground"),
    ("primary", "primary"),
    ("primary-foreground", "primaryForeground"),
    ("secondary", "secondary"),
    ("secondary-foreground", "secondaryForeground"),
    ("muted", "muted"),
    ("muted-foreground", "mutedForeground"),
    ("accent", "accent"),
    ("accent-foreground", "accentForeground"),
    ("destructive", "destructive"),
    ("border", "border"),
    ("input", "input"),
    ("ring", "ring"),
]


def main():
    if len(sys.argv) < 3:
        print("Usage: python3 gen-theme.py <design.json> <output.css>", file=sys.stderr)
        sys.exit(1)

    design_path = sys.argv[1]
    output_path = sys.argv[2]

    with open(design_path) as f:
        data = json.load(f)

    if isinstance(data, list):
        data = data[0]

    theme = data["theme"]
    colors = theme["colors"]
    custom = theme.get("customColors", {})

    # ── :root block ──
    lines = [
        "/* Generated by gen-theme.py — do not edit manually. */",
        "/* NEVER add a .dark {} block — dark mode is not supported. */",
        "",
        ":root {",
    ]

    # Standard color tokens
    for css_name, json_key in STANDARD_COLOR_MAPPING:
        val = colors.get(json_key, "#000000")
        lines.append(f"  --{css_name}: {val};")

    # Radius
    lines.append(f"  --radius: {theme.get('radius', '0.5rem')};")
    lines.append(f"  --radius-button: {theme.get('radiusButton', theme.get('radius', '0.5rem'))};")

    # Fonts
    fonts = theme.get("fonts", {})
    lines.append(f"  --font-sans: {fonts.get('sans', 'system-ui, sans-serif')};")
    lines.append(f"  --font-display: {fonts.get('display', 'system-ui, sans-serif')};")
    lines.append(f"  --font-mono: {fonts.get('mono', 'ui-monospace, monospace')};")
    lines.append(f"  --font-serif: {fonts.get('serif', 'Georgia, serif')};")

    # Custom tokens
    if custom:
        lines.append("")
        lines.append("  /* Custom tokens */")
        for key, val in custom.items():
            lines.append(f"  --{key}: {val};")

    lines.append("}")

    # ── @theme inline block for custom tokens ──
    if custom:
        lines.append("")
        lines.append("/* Tailwind mappings for custom tokens */")
        lines.append("@theme inline {")
        for key in custom:
            lines.append(f"  --color-{key}: var(--{key});")
        lines.append("}")

    lines.append("")

    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    print(f"✓ Wrote {output_path} ({len(custom)} custom tokens)")


if __name__ == "__main__":
    main()
