#!/usr/bin/env node
/**
 * Generate theme.css from a design.json file.
 *
 * Usage: node gen-theme.js <design.json> <output.css>
 *
 * Produces a self-contained theme.css with:
 *   - :root {} block with all standard + custom CSS variables
 *   - @theme inline {} block mapping custom tokens to Tailwind classes
 *   - NO .dark {} block (dark mode is not supported)
 */
const fs = require("fs");
const path = require("path");

const STANDARD_COLOR_MAPPING = [
	["background", "background"],
	["foreground", "foreground"],
	["card", "card"],
	["card-foreground", "cardForeground"],
	["popover", "popover"],
	["popover-foreground", "popoverForeground"],
	["primary", "primary"],
	["primary-foreground", "primaryForeground"],
	["secondary", "secondary"],
	["secondary-foreground", "secondaryForeground"],
	["muted", "muted"],
	["muted-foreground", "mutedForeground"],
	["accent", "accent"],
	["accent-foreground", "accentForeground"],
	["destructive", "destructive"],
	["border", "border"],
	["input", "input"],
	["ring", "ring"],
];

function main() {
	if (process.argv.length < 4) {
		process.stderr.write(
			"Usage: node gen-theme.js <design.json> <output.css>\n",
		);
		process.exit(1);
	}

	const designPath = process.argv[2];
	const outputPath = process.argv[3];

	let data = JSON.parse(fs.readFileSync(designPath, "utf-8"));
	if (Array.isArray(data)) data = data[0];

	const theme = data.theme;
	const colors = theme.colors;
	const custom = theme.customColors || {};

	const lines = [
		"/* Generated by gen-theme.js — do not edit manually. */",
		"/* NEVER add a .dark {} block — dark mode is not supported. */",
		"",
		":root {",
	];

	// Standard color tokens
	for (const [cssName, jsonKey] of STANDARD_COLOR_MAPPING) {
		const val = colors[jsonKey] || "#000000";
		lines.push(`  --${cssName}: ${val};`);
	}

	// Radius
	lines.push(`  --radius: ${theme.radius || "0.5rem"};`);
	lines.push(
		`  --radius-button: ${theme.radiusButton || theme.radius || "0.5rem"};`,
	);

	// Fonts
	const fonts = theme.fonts || {};
	lines.push(`  --font-sans: ${fonts.sans || "system-ui, sans-serif"};`);
	lines.push(
		`  --font-display: ${fonts.display || "system-ui, sans-serif"};`,
	);
	lines.push(`  --font-mono: ${fonts.mono || "ui-monospace, monospace"};`);
	lines.push(`  --font-serif: ${fonts.serif || "Georgia, serif"};`);

	// Custom tokens
	const customKeys = Object.keys(custom);
	if (customKeys.length > 0) {
		lines.push("");
		lines.push("  /* Custom tokens */");
		for (const key of customKeys) {
			lines.push(`  --${key}: ${custom[key]};`);
		}
	}

	lines.push("}");

	// @theme inline block for custom tokens
	if (customKeys.length > 0) {
		lines.push("");
		lines.push("/* Tailwind mappings for custom tokens */");
		lines.push("@theme inline {");
		for (const key of customKeys) {
			lines.push(`  --color-${key}: var(--${key});`);
		}
		lines.push("}");
	}

	lines.push("");

	fs.writeFileSync(outputPath, lines.join("\n"));
	process.stdout.write(
		`✓ Wrote ${outputPath} (${customKeys.length} custom tokens)\n`,
	);
}

main();
